### ISSUE TITLE
Problem with multiple context?

### ISSUE THREAD

**Issue by shepaldo** [apnix/frontendeditor#5]
I have had no problem working with the excellent Fronteneditor in the past when the site has a single context, but today I am working with a site containing 3 contexts: "Federation", "Appleshaw" and "Kimpton". Frontendeditor works perfectly for the first context, "Federation", but the editing button does no appear for the other 2 contexts "Appleshaw" and "Kimpton". Is this expected behaviour or is the problem at my end?

Thanks, Andy

![contexts](https://user-images.githubusercontent.com/718308/122933067-31c43800-d366-11eb-9b5f-0479ffb31f66.jpg)
![as](https://user-images.githubusercontent.com/718308/122933297-6afca800-d366-11eb-983f-376cd67dedb6.jpg)

**Comment by apnix** [comment]
I have not tested Fronteneditor for multi-context sites. I'm gonna do it next week and write more on the results.

**Comment by shepaldo** [comment]
Hello Artemiy, thanks for the reply. You could probably make a more elegant solution, but in my case a quick fix was to hard code the asset path in the frontendeditor plugin, line 9, i.e. changed 'assets/... to '/assets/...

$frontendeditorAssetsPath = $modx->getOption('frontendeditor.assets_path', null, '/assets/components/frontendeditor/');

KR,

Andy

**Comment by apnix** [comment]
Sorry for late answer.
I think the problem is that the base tag is either not specified or referes the context path, and the resource directory is located at the root of the site. In my opinion, loading resources from the base url is normal and should not be changed.
I think in your case the best solution would be to create a key _frontendeditor.assets_path_ with the value _/assets/components/frontendeditor/_ in system settings. This will allow to avoid hardcoding.
![image](https://user-images.githubusercontent.com/7911550/124464147-7b684600-dd9c-11eb-9b5e-bcf727a1a7fd.png)

**Comment by shepaldo** [comment]
That sounds like a good plan!
